### ISSUE TITLE
Storage & Retrieval work with spec-actors in Lotus

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/go-fil-markets#131]
Acceptance Criteria: Get TestAPIDealFlowReal to pass

**Comment by mishmosh** [comment]
- lotus has a big integration test for making storage deal flow that's not passing
- first 2 errors were is in the node adapter
- next few errors are in core lotus codebase
- @hannahhoward expects to have these fixed in the next few hours

- also incidentally found some unrelated errors in how lotus is using specs actors (eg deserialization in paych actor, multisig actor), will flag in chat
