### ISSUE TITLE
Remove all hardcoded datastore prefixes

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/go-fil-markets#256]
Generally, the node should configure the prefix on any datastore usage.

This ticket involves:
- [ ] remove places in code where datastore prefix is marked for this issue (TODOs should be present)
- [ ] cut a new release
- [ ] update both node implementations and provide data store default prefixes (since node maintainers will likely not know enough to set this up right initially.

**Comment by shannonwells** [comment]
@hannahhoward Currently lotus is on go-fil-markets v0.2.3,  so API update work will be needed to update from there to v0.2.6

**Comment by shannonwells** [comment]
This branch of lotus (https://github.com/filecoin-project/lotus/pull/1802) is now passing tests w/ the latest commits using the 0.2.7 branch (https://github.com/filecoin-project/go-fil-markets/pull/259).  The branch of go-filecoin is also passing tests (assuming this last rebase passes) with same (https://github.com/filecoin-project/go-filecoin/pull/4155).  Because there is some additional work needed we'll need to do further updates and these changes will be included with @hannahhoward 's changes and released together.
